version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin  # do not use this for production deployments
      - PGPASSWORD=admin  # do not use this for production deployments
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    networks:
      persistence:

  tng-kds:
    build: .
    image: ghcr.io/worldhealthorganization/tng-key-distribution/tng-key-distribution:latest
    volumes:
      - ./certs:/ec/prod/app/san/dgc
      - ./logs:/logs
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=cloud
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_JNDI_NAME=false
      - SPRING_JPA_DATABASEPLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin # do not use this for production deployments
    depends_on:
      - postgres
    networks:
      backend:
      persistence:

networks:
  persistence:
  backend:
