apiVersion: v1
kind: Service
metadata:
  name: {{ include "tngkds.fullname" . }}-service
  labels:
    {{- include "tngkds.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{ range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | int}}
      nodePort: {{ .nodePort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{ end }}
  selector:
    {{- include "tngkds.selectorLabels" . | nindent 4 }}
