kind: Secret
apiVersion: v1
metadata:
  name: tng-distribution-pull-secret
  namespace: {{ .Release.Namespace }}
data:
	.dockerconfigjson: {{ .Values.secrets.dockerPull }}
type: kubernetes.io/dockerconfigjson