server:
  port: 8080
spring:
  application:
    name: tng-key-distribution
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: ''
  jackson:
    deserialization:
      read-unknown-enum-values-using-default-value: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yaml
  h2:
    console:
      enabled: true
      path: /h2-console
  task:
    scheduling:
      pool:
        size: 5
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health
info:
  name: ${spring.application.name}
  profiles: ${spring.profiles.active}
universal:
  resolver: "https://dev.uniresolver.io/1.0/identifiers"
dgc:
  clients:
    proxy:
      enabled: false
      host:
      port: -1
  certificatesDownloader:
    timeInterval: 1800000
    lockLimit: 3600000
  trustedIssuerDownloader:
    enabled: true
    timeInterval: 1800000
    lockLimit: 3600000
    static-trusted-issuer:
      - name: WHO Trustlist (DEV)
        country: WH
        type: did
        url: did:web:tng-cdn-dev.who.int:trustlist
        signature: No-Signature # required because of DB restrictions
        domain: DCC
    enable-trusted-issuer-resolving: false
  gateway:
    connector:
      enabled: true
      endpoint: https://tng-dev.who.int
      proxy:
        enabled: false
        host: 10.24.19.86
        port: 8080
      max-cache-age: 300
      tls-trust-store: #CA of TNG Gateway of TLS certificate
        alias: tng-tls-server-certificate
        password: dgcg-p4ssw0rd
        path: certs/tng_tls_server_truststore.p12
      tls-key-store: # client cert key pair of participant
        alias: clientcredentials
        password: dgcg-p4ssw0rd
        path: certs/tls_key_store.p12
      trust-anchor: # TA pem file of TNG that was used for signing
        alias: trustanchor
        password: dgcg-p4ssw0rd
        path: certs/trustanchor_store.jks
      enable-ddcc-support: true
  did:
    cron: "0 */10 * * * *"
    enableDidGeneration: true
    enableKidLevelDidGeneration: false
    didUploadProvider: local-file
    localFile:
      directory: ./tmp/kdsgitworkdir/tng-cdn-dev/v2
      file-name: did.json
    git:
      workdir: ./tmp/kdsgituploader # oon clonind will checkout e.g. tng-cdn-dev
      prefix: v2 #for copy action into git workdir from local file exporter path
      url: https://github.com/WorldHealthOrganization/tng-cdn-dev
      pat:
    didSigningProvider: dummy
    ld-proof-verification-method: did:web:dummy.net
    did-id: did:web:abc
    trust-list-path: trustlist
    trust-list-ref-path: trustlist-ref
    did-controller: did:web:def
    contextMapping:
      "[https://www.w3.org/ns/did/v1]": did_v1.json
      "[https://w3id.org/security/suites/jws-2020/v1]": jws-2020_v1.json
      "[https://worldhealthorganization.github.io/smart-trust/tng-context/v1]": tng-context_v1.json
#    virtualCountries:
#      XA: XXA
#      XB: XXB
#      XO: XXO
#      XL: XCL
#      WH: WHO
#      XG: XXG
#      XS: XXS
#      XH: XXH
#      XC: XXC
#      XD: XXD
#      XE: XXE
#      XF: XXF
#      XI: XXI
#      XJ: XXJ
#      XK: XXK
#      XM: XML
#      YK: XYK
#      XN: XXN
#      XP: XXP
#      IO: IOM
    group-deny-list:
      - AUTHENTICATION
      - UPLOAD
    group-name-mapping:
      CSCA: SCA
