server:
  port: 8080
spring:
  application:
    name: tng-key-distributions
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: $ {password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.xml
  h2:
    console:
      enabled: true
      path: /h2-console
  task:
    scheduling:
      pool:
        size: 5
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: info,health
info:
  name: ${spring.application.name}
  profiles: ${spring.profiles.active}
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
kds:
  gateway:
    connector:
      enabled: true
      endpoint: https://tng-dev.who.int
      tls-trust-store: #CA of TNG Gateway of TLS certificate
        password: ${password}
        path: certs\tng_tls_server_truststore.p12
      tls-key-store: # client cert key pair of participant
        alias: tng-tls-server-certificate
        password: ${password}
        path: certs\tls_key_store.p12
      trust-anchor: # TA pem file of TNG that was used for signing
        alias: trustanchor
        password: ${password}
        path: certs\trustanchor_store.jks
      proxy:
        host: sia-lb.telekom.de
        port: 8080
        enabled: true
        max-cache-age: 300
  certificatesDownloader:
    timeInterval: 1800000
    lockLimit: 3600000
  trustedIssuerDownloader:
    enabled: true
    timeInterval: 1800000
    lockLimit: 3600000
  trustlistDownloader:
    enabled: true
    timeInterval: 1800000
    lockLimit: 3600000
     
#  gateway:
 #   connector:
 #     enabled: false
 