server:
  port: 8080
spring:
  application:
    name: tng-key-distribution
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.xml
  h2:
    console:
      enabled: true
      path: /h2-console
  task:
    scheduling:
      pool:
        size: 5
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health
info:
  name: ${spring.application.name}
  profiles: ${spring.profiles.active}
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
dgc:
  certificatesDownloader:
    timeInterval: 1800000
    lockLimit: 3600000
  trustedIssuerDownloader:
    enabled: true
    timeInterval: 1800000
    lockLimit: 3600000
  gateway:
    connector:
#      enabled: false
      enabled: true
      endpoint: https://tng-dev.who.int
      proxy:
        enabled: false
      max-cache-age: 300
      tls-trust-store: #CA of TNG Gateway of TLS certificate
        alias: tng-tls-server-certificate
        password: dgcg-p4ssw0rd
        path: certs/tng_tls_server_truststore.p12
      tls-key-store: # client cert key pair of participant
        alias: clientcredentials
        password: dgcg-p4ssw0rd
        path: certs/tls_key_store.p12
      trust-anchor: # TA pem file of TNG that was used for signing
        alias: trustanchor
        password: dgcg-p4ssw0rd
        path: certs/trustanchor_store.jks

universal:
  resolver: "https://dev.uniresolver.io/1.0/identifiers"
