server:
  port: 8080
spring:
  application:
    name: tng-key-distribution
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: ''
  jackson:
    deserialization:
      read-unknown-enum-values-using-default-value: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yaml
  h2:
    console:
      enabled: true
      path: /h2-console
  task:
    scheduling:
      pool:
        size: 5
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health
info:
  name: ${spring.application.name}
  profiles: ${spring.profiles.active}
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
universal:
  resolver: "https://dev.uniresolver.io/1.0/identifiers"
dgc:
  clients:
    proxy:
      enabled: false
      host:
      port: -1
  certificatesDownloader:
    timeInterval: 1800000
    lockLimit: 3600000
  trustedIssuerDownloader:
    enabled: true
    timeInterval: 1800000
    lockLimit: 3600000
  gateway:
    connector:
      enabled: false
      endpoint: ${DGC_GATEWAY_CONNECTOR_ENDPOINT}
      proxy:
        enabled: false
      max-cache-age: 300
      tls-trust-store:
        password: ${DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PASSWORD}
        path: ${DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PATH}
      tls-key-store:
        alias: ${DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_ALIAS}
        password: ${DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PASSWORD}
        path: ${DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PATH}
      trust-anchor:
        alias: ${DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_ALIAS}
        password: ${DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_PASSWORD}
        path: ${DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_PATH}
  static-trusted-issuer:
    - name: WHO Trustlist (DEV)
      country: WH
      type: did
      url: did:web:tng-cdn-dev.who.int:trustlist
      signature: No-Signature # required because of DB restrictions
