# Default values for tngkds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tngkds-postgres:
  path: /()(*)
  port: 5432

  asPod:
    enabled: false # run db as Service or Pod,set in conjunction with tngkds-backend

tngkds-backend:
  image:
    tag: <kds-image-tag>
  liquibaseImage:
    tag: <liquibase-image-tag(initcontainer)>
  path: /()(*)
  port: 8080
  psql:
    serviceName: postgresql-d01.postgres.database.azure.com
    port: 5432
    dbName: kdsdb
    cluster: svc.cluster.local # will be used if db is running as Pod
    username:
    password:
    asPod:
      enabled: false # run db as Service or Pod,set in conjunction with tngkds-postgres
