kind: Secret
apiVersion: v1
metadata:
  name: mtls-secret
  namespace: {{ .Release.Namespace }}
data:
  tls_key_store.p12: {{ .Values.secrets.mtls.tlsKeyStore }}
  tng_tls_server_truststore.p12: {{ .Values.secrets.mtls.tlsServerTrustStore }}
  trustanchor_store.jks: {{ .Values.secrets.mtls.tlsTrustAnchorStore }}
type: Opaque
