# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ include "tngkds-backend.fullname" . }}-cfg
#   namespace: {{ .Release.Namespace }}
# data:
#   host: "{{ .Values.configMap.data.host }}"
#   dbname: "{{ .Values.configMap.data.dbName }}"
