apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-changelog
data:
  changelog.yaml: |
    databaseChangeLog:
      - include:
          file: init-tables.yaml
      - include:
          file: alter-signer-information.yaml
      - include:
          file: create-info-table.yaml
      - include:
          file: create-trusted-issuer-table.yaml
  init-tables.yaml: |
    databaseChangeLog:
      - objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      - changeSet:
          id: shedlock-create
          author: admin
          changes:
            - createTable:
                tableName: shedlock
                columns:
                  - column:
                      name: id
                      type: bigint
                      constraints:
                        primaryKey: true
                        primaryKeyName: pk_shedlock
                        nullable: false
                  - column:
                      name: name
                      type: varchar(64)
                      constraints:
                        nullable: false
                        unique: true
                  - column:
                      name: lock_until
                      type: datetime
                      constraints:
                        nullable: false
                  - column:
                      name: locked_at
                      type: datetime
                      constraints:
                        nullable: false
                  - column:
                      name: locked_by
                      type: varchar(255)
                      constraints:
                        nullable: false
      - changeSet:
          id: shedlock-sequence
          author: admin
          changes:
            - addAutoIncrement:
                tableName: shedlock
                columnName: id
                columnDataType: bigint
                startWith: 1
                incrementBy: 1
      - changeSet:
          id: signer-information-create
          author: admin
          changes:
            - createTable:
                tableName: signer_information
                columns:
                  - column:
                      name: id
                      type: bigint
                      constraints:
                        primaryKey: true
                        primaryKeyName: pk_signer_information
                        nullable: false
                  - column:
                      name: kid
                      type: varchar(50)
                      constraints:
                        nullable: false
                  - column:
                      name: created_at
                      type: datetime
                      constraints:
                        nullable: false
                  - column:
                      name: raw_data
                      type: varchar(4096)
                      constraints:
                        nullable: false
      - changeSet:
          id: signer-information-sequence
          author: admin
          changes:
            - addAutoIncrement:
                tableName: signer_information
                columnName: id
                columnDataType: bigint
                startWith: 1
                incrementBy: 1
  alter-signer-information.yaml: |
    databaseChangeLog:
    - objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
    - changeSet:
        id: delete old data
        author: admin
        changes:
          - delete:
              tableName: signer_information
    - changeSet:
        id: alter-signer-information
        author: admin
        changes:
          - addColumn:
              tableName: signer_information
              columns:
                - column:
                    name: country
                    type: varchar(2)
                - column:
                    name: thumbprint
                    type: varchar(512)
                - column:
                    name: updated_at
                    type: timestamp with time zone
                    constraints:
                      nullable: false
                - column:
                    name: deleted
                    type: boolean
  create-info-table.yaml: |
    databaseChangeLog:
    - changeSet:
        id: create-info-table
        author: admin
        changes:
          - createTable:
              tableName: vs_info
              columns:
                - column:
                    name: identifier_key
                    type: varchar(255)
                    constraints:
                      primaryKey: true
                      primaryKeyName: pk_vs_info
                      nullable: false
                - column:
                    name: property_value
                    type: varchar(255)
  create-trusted-issuer-table.yaml: |
    databaseChangeLog:
    - changeSet:
        id: create-trusted-issuer-table
        author: admin
        changes:
          - createTable:
              tableName: trusted_issuer
              columns:
                - column:
                    autoIncrement: true
                    name: id
                    type: bigint
                    constraints:
                      primaryKey: true
                      primaryKeyName: pk_trusted_issuer
                      nullable: false
                - column:
                    name: etag
                    type: varchar(36)
                    constraints:
                      nullable: false
                - column:
                    name: created_at
                    type: timestamp with time zone
                    constraints:
                      nullable: false
                - column:
                    name: country
                    type: varchar(2)
                    constraints:
                      nullable: false
                - column:
                    name: url
                    type: varchar(1024)
                    constraints:
                      nullable: false
                - column:
                    name: name
                    type: varchar(512)
                    constraints:
                      nullable: false
                - column:
                    name: url_type
                    type: varchar(25)
                    constraints:
                      nullable: false
                - column:
                    name: thumbprint
                    type: varchar(64)
                - column:
                    name: ssl_public_key
                    type: varchar(2048)
                - column:
                    name: key_storage_type
                    type: varchar(128)
                - column:
                    name: signature
                    type: varchar(6000)
                    constraints:
                      nullable: false
