apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tngkds-backend.fullname" . }}
  labels:
    {{- include "tngkds-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tngkds-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "tngkds-backend.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: gateway-connector-tls-keystore
          ConfigMap:
            name: tng_kds_TlsTruststoreConfigMap
        - name: gateway-connector-tls-truststore
          ConfigMap:
            name: tng_kds_TlsKeystoreConfigMap
        - name: tng-kds-tls-truststore
          secret:
            secretName: tng-kds-tls-truststore
        - name: tng-kds-tls-keystore
          secret:
            secretName: tng-kds-tls-keystore
            
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{ range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
          {{ end }}
          volumeMounts:
            - name: gateway-connector-tls-keystore
              mountPath: /mnt/{{- .Values.gateway.connector.TlsKeystore | quote | }}
            - name: gateway-connector-tls-truststore
              mountPath: /mnt/{{- .Values.gateway.connector.TlsTruststore | quote | }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.server.port }}"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profile }}
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.psql.serviceName }}.{{ .Release.Namespace }}.{{ .Values.psql.cluster }}:{{ .Values.psql.port }}/{{ .Values.psql.dbName }}"
            - name: SPRING_DATASOURCE_DRIVERCLASSNAME
              value: "org.postgresql.Driver"
            - name: SPRING_DATASOURCE_JNDI_NAME
              value: "false"
            - name: SPRING_JPA_DATABASEPLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "tngkds-backend.fullname" . }}-secret
                  key: pgUser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "tngkds-backend.fullname" . }}-secret
                  key: pgPassword
            - name: DGC_GATEWAY_CONNECTOR_ENDPOINT
              value: {{ .Values.gateway.connector.Endpoint }}
            - name: DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PATH
              value: {{ .Values.gateway.connector.TlsTruststore }}
            - name: DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "tng-kds-tls-truststore.password-secret"
                  key: gatewayConnectorTlsTruststorePassword
            - name: DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PATH
              value: {{ .Values.gateway.connector.TlsKeystore }}
            - name: DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "tng-kds-tls-keystore.password-secret"
                  key: gatewayConnectorTlsKeystorePassword
            - name: DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_ALIAS
              value: {{ .Values.gateway.connector.TrustanchorAlias }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
