apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tngkds-backend.fullname" . }}
  labels:
    {{- include "tngkds-backend.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tngkds-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "tngkds-backend.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{ range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
          {{ end }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.server.port }}"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profile }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.db.url | quote }}
            - name: SPRING_DATASOURCE_DRIVERCLASSNAME
              value: {{ .Values.db.driverclass | quote }}
            - name: SPRING_DATASOURCE_JNDI_NAME
              value: "false"
            - name: SPRING_JPA_DATABASEPLATFORM
              value: {{ .Values.db.plattform | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.username | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: DGC_GATEWAY_CONNECTOR_TLS_TRUST_STORE_PATH
              value: {{ .Values.gateway.connector.tls_trust_store.path }}
            - name: DGC_GATEWAY_CONNECTOR_TLS_TRUST_STORE_PASSWORD
              value: {{ .Values.gateway.connector.tls_trust_store.password | quote }}
            - name: DGC_GATEWAY_CONNECTOR_TLS_TRUST_STORE_ALIAS
              value: {{ .Values.gateway.connector.tls_trust_store.alias }}
            - name: DGC_GATEWAY_CONNECTOR_TLS_KEY_STORE_PATH
              value: {{ .Values.gateway.connector.tls_key_store.path }}
            - name: DGC_GATEWAY_CONNECTOR_TLS_KEY_STORE_PASSWORD
              value: {{ .Values.gateway.connector.tls_key_store.password | quote }}
            - name: DGC_GATEWAY_CONNECTOR_TLS_KEY_STORE_ALIAS
              value: {{.Values.gateway.connector.tls_key_store.alias }}
            - name: DGC_GATEWAY_CONNECTOR_TRUST_ANCHOR_PATH
              value: {{ .Values.gateway.connector.trust_anchor.path }}
            - name: DGC_GATEWAY_CONNECTOR_TRUST_ANCHOR_PASSWORD
              value: {{ .Values.gateway.connector.trust_anchor.password | quote }}
            - name: DGC_GATEWAY_CONNECTOR_TRUST_ANCHOR_ALIAS
              value: {{ .Values.gateway.connector.trust_anchor.alias }}
            - name: DGC_GATEWAY_CONNECTOR_ENABLED
              value: {{ .Values.gateway.connector.enabled | quote }}
            - name: DGC_GATEWAY_CONNECTOR_ENDPOINT
              value: {{ .Values.gateway.connector.endpoint }}
          {{- if .Values.did.enableDidGeneration }}
            - name: DGC_DID_CRON
              value: "{{ .Values.did.cron }}"
            - name: DGC_DID_DIDUPLOADPROVIDER
              value: "{{ .Values.did.didUploadProvider }}"
            - name: DGC_DID_LOCALFILE_DIRECTORY
              value: "{{ .Values.did.localFile.directory }}"
            - name: DGC_DID_LOCALFILE_FILENAME
              value: "{{ .Values.did.localFile.filename }}"
            - name: DGC_DID_GIT_WORKDIR
              value: "{{ .Values.did.git.workdir }}"
            - name: DGC_DID_GIT_PREFIX
              value: "{{ .Values.did.git.prefix }}"
            - name: DGC_DID_GIT_URL
              value: "{{ .Values.did.git.url }}"
            - name: DGC_DID_GIT_PAT
              value: "{{ .Values.did.git.pat }}"
            - name: DGC_DID_DIDSIGNINGPROVIDER
              value: "{{ .Values.did.didSigningProvider }}"
            - name: DGC_DID_LDPROOFVERIFICATIONMETHOD
              value: "{{ index .Values.did "ld-proof-verification-method" }}"
            - name: DGC_DID_DIDID
              value: "{{ index .Values.did "did-id" }}"
            - name: DGC_DID_TRUSTLISTPATH
              value: "{{ index .Values.did "trust-list-path" }}"
            - name: DGC_DID_TRUSTLISTREFPATH
              value: "{{ index .Values.did "trust-list-ref-path" }}"
            - name: DGC_DID_DIDCONTROLLER
              value: "{{ index .Values.did "did-controller" }}"
            - name: DGC_DID_TRUSTLISTIDPREFIX
              value: "{{ index .Values.did "trust-list-id-prefix" }}"
            - name: DGC_DID_TRUSTLISTCONTROLLEPREFIX
              value: "{{ index .Values.did "trust-list-controller-prefix" }}"
           {{- range $key, $value := .Values.did.virtualCountries }}
            - name: DGC_DID_VIRTUALCOUNTRIES_{{ $key | toString | upper }}
              value: "{{ $value }}"
           {{- end }}
            - name: DGC_DID_GROUPDENYLIST
              value: "{{ join "," (index .Values.did "group-deny-list") }}"
           {{- range $key, $value := index .Values.did "group-name-mapping" }}
            - name: DGC_DID_GROUPNAMEMAPPING_{{ $key | toString | upper }}
              value: "{{ $value }}"
           {{- end }}
          {{- end }}
          volumeMounts:
            - name: secrets-jks
              mountPath: /certs
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: secrets-jks
          secret:
            secretName: mtls-secret
            items:
              - key: tls_key_store.p12
                path: tls_key_store.p12
              - key: trustanchor_store.jks
                path: trustanchor_store.jks
              - key: tng_tls_server_truststore.p12
                path: tng_tls_server_truststore.p12
