apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tngkds-postgres.fullname" . }}-pv-claim
  labels:
    {{- include "tngkds-postgres.labels" . | nindent 4 }}
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
