apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kds.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.postgres.replicas | int }}
  selector:
    matchLabels:
      {{- include "kds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kds.templateLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "kds.fullname" . }}-postgres
          image: {{ .Values.postgres.image }}:{{ .Values.postgres.tag }}
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
