name: Release Charts

on:
  release:
    types:
      - created
  workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: "k8s/helm/tngkds" # Specify the path to your charts directory
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
